# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20170803_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u83dc\u5355')),
                ('url_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'url',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(blank=True, to='crm.Menu'),
        ),
    ]
